JobsApp/Controllers/AnnouncementController.cs
using JobsApp.Data;
using JobsApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace JobsApp.Controllers
{
    public class AnnouncementController : Controller
    {
        private Repository.AnnouncementRepository _repository;

        public AnnouncementController(ApplicationDbContext dbContext)
        {
            _repository = new Repository.AnnouncementRepository(dbContext);
        }

        // GET: AnnouncementController
        public ActionResult Index()
        {
            var announcements = _repository.GetAllAnnouncements();
            return View("IndexAnnouncement", announcements);
        }

        [Authorize(Roles = "Company")]
        public ActionResult MyAnnouncements()
        {
            var announcements = _repository.GetAllAnnouncementsByProfile(User.Identity.Name);
            return View("MyAnnouncements", announcements);
        }

        // GET: AnnouncementController/Details/5
        public ActionResult Details(Guid id)
        {
            TempData["announcement"] = id;
            TempData["announcementApplications"] = id;
            var model = _repository.GetAnnouncementById(id);
            return View("AnnouncementDetails", model);
        }

        // GET: AnnouncementController/Create
        [Authorize(Roles = "Company")]
        public ActionResult Create()
        {
            var model = new AnnouncementModel();
            return View("CreateAnnouncement", model);
        }

        // POST: AnnouncementController/Create
        [Authorize(Roles = "Company")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                AnnouncementModel model = new AnnouncementModel();
                var task = TryUpdateModelAsync(model);
                task.Wait();
                _repository.InsertAnnouncement(model, User.Identity.Name);
                return View("CreateAnnouncement");
            }
            catch
            {
                return View("CreateAnnouncement");
            }
        }

        // GET: AnnouncementController/Edit/5
        [Authorize(Roles = "Company")]
        public ActionResult Edit(Guid id)
        {
            var model = _repository.GetAnnouncementById(id);
            return View("EditAnnouncement", model);
        }

        // POST: AnnouncementController/Edit/5
        [Authorize(Roles = "Company")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                var model = new AnnouncementModel();
                var task = TryUpdateModelAsync(model);
                task.Wait();
                _repository.UpdateAnnouncement(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index", id);
            }
        }

        // GET: AnnouncementController/Delete/5
        [Authorize(Roles = "Company")]
        public ActionResult Delete(Guid id)
        {
            var model = _repository.GetAnnouncementById(id);
            return View("DeleteAnnouncement", model);
        }

        // POST: AnnouncementController/Delete/5
        [Authorize(Roles = "Company")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                var model = _repository.GetAnnouncementById(id);
                _repository.DeleteAnnouncement(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("DeleteAnnouncement", id);
            }
        }
    }
}

JobsApp/Controllers/ApplicationController.cs
using JobsApp.Data;
using JobsApp.Models;
using JobsApp.Models.DBObjects;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace JobsApp.Controllers
{
    public class ApplicationController : Controller
    {
        private Repository.ApplicationRepository _repository;
        private Repository.AnnouncementRepository announcementRepository;

        public ApplicationController(ApplicationDbContext dbContext)
        {
            _repository = new Repository.ApplicationRepository(dbContext);
            announcementRepository = new Repository.AnnouncementRepository(dbContext);
        }

        // GET: ApplicationController
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Candidate")]
        public ActionResult MyApplications()
        {
            var myapplications = _repository.GetAllApplicationsByCandidateProfile(User.Identity.Name);
            return View("MyApplications", myapplications);
        }

        [Authorize(Roles = "Company")]
        public ActionResult ApplicationsToAnnouncement()
        {
            if (TempData["announcementApplications"] != null )
            {
                var announcementId = new Guid(TempData["announcementApplications"].ToString());
                var applicationsToAnnouncement = _repository.GetAllApplicationsByAnnouncement(announcementId);
                return View("ApplicationsToAnnouncement", applicationsToAnnouncement);
            }
            else
            {
                var myAnnouncements = announcementRepository.GetAllAnnouncementsByProfile(User.Identity.Name);
                return View("~/Views/Announcement/MyAnnouncements.cshtml", myAnnouncements);
            }    
        }

        // GET: ApplicationController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ApplicationController/Create
        [Authorize(Roles = "Candidate")]
        public ActionResult Create()
        {
            var model = new ApplicationModel();
            return View("CreateApplication", model);
        }

        // POST: ApplicationController/Create
        [Authorize(Roles = "Candidate")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                Models.ApplicationModel model = new Models.ApplicationModel();
                var announcement = new Guid(TempData["announcement"].ToString());
                var cv = new Guid(TempData["cv"].ToString());
                var task = TryUpdateModelAsync(model);
                task.Wait();
                _repository.InsertApplication(model, cv, announcement);
                return View("CreateApplication");
            }
            catch
            {
                return View("CreateApplication");
            }
        }

        // GET: ApplicationController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ApplicationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ApplicationController/Delete/5
        [Authorize(Roles = "Candidate")]
        public ActionResult Delete(Guid id)
        {
            var model = _repository.GetApplicationById(id);
            return View("Delete", model);
        }

        // POST: ApplicationController/Delete/5
        [Authorize(Roles = "Candidate")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                var model = _repository.GetApplicationById(id);
                _repository.DeleteApplication(model);
                return RedirectToAction("MyApplications");
            }
            catch
            {
                return View("Delete", id);
            }
        }
    }
}

JobsApp/Controllers/ProfileController.cs
using JobsApp.Data;
using JobsApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace JobsApp.Controllers
{
    public class ProfileController : Controller
    {
        private Repository.ProfileRepository _repository;

        public ProfileController(ApplicationDbContext dbContext)
        {
            _repository = new Repository.ProfileRepository(dbContext);
        }

        [Authorize(Roles = "Candidate, Company, Admin")]
        // GET: ProfileController
        public ActionResult Index()
        {
            var profiles = _repository.GetAllProfiles();
            return View("IndexProfiles", profiles);
        }

        // GET: ProfileController/Details/5
        public ActionResult Details(string id)
        {
            var model = _repository.GetProfileById(id);
            return View("ProfileDetails", model);
        }
        
        [Authorize(Roles = "Candidate, Company, Admin")]
        // GET: ProfileController/Create
        public ActionResult Create()
        {
            var model = new ProfileModel();
            model.Idprofile = User.Identity.Name;
            return View("CreateProfile", model);
        }

        // POST: ProfileController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Candidate, Company, Admin")]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                Models.ProfileModel model = new Models.ProfileModel();

                var task = TryUpdateModelAsync(model);
                task.Wait();
                if (task.Result)
                {
                    _repository.InsertProfile(model);
                }

                return View("ProfileDetails", model);
            }
            catch
            {
                return View("CreateProfile");
            }
        }

        // GET: ProfileController/Edit/5
        public ActionResult Edit(string id)
        {
            var model = _repository.GetProfileById(id);
            return View("EditProfile", model);
        }

        // POST: ProfileController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, IFormCollection collection)
        {
            try
            {
                var model = new ProfileModel();

                var task = TryUpdateModelAsync(model);
                task.Wait();

                if (task.Result)
                {
                    _repository.UpdateProfile(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", id);
                }
            }
            catch
            {
                return RedirectToAction("Index", id);
            }
        }

        // GET: ProfileController/Delete/5
        public ActionResult Delete(string id)
        {
            var model = _repository.GetProfileById(id);
            return View("DeleteProfile", model);
        }

        // POST: ProfileController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id, IFormCollection collection)
        {
            try
            {
                var model = _repository.GetProfileById(id);
                _repository.DeleteProfile(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("DeleteProfile", id);
            }
        }
    }
}

JobsApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JobsApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JobsApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JobsApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(User.Identity.IsAuthenticated)
                        {
                           <li class="nav-item">
                                @Html.ActionLink("My Profile", "Details", "Profile", new {  id = User.Identity.Name }, new { @class = "nav-link text-dark" })
                            </li> 
                        }
                        <li class="nav-item">
                            @Html.ActionLink("Announcements", "Index", "Announcement", null, new { @class = "nav-link text-dark" })
                        </li>
                        @if (User.IsInRole("Candidate"))
                        {
                            <li class="nav-item">
                                @Html.ActionLink("My Applications", "MyApplications", "Application", new {  id = User.Identity.Name }, new { @class = "nav-link text-dark" })
                            </li> 
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - JobsApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>