JobsApp/Models/DBObjects/Announcement.cs
using System;
using System.Collections.Generic;

namespace JobsApp.Models.DBObjects
{
    public partial class Announcement
    {
        public Announcement()
        {
            Applications = new HashSet<Application>();
        }

        public Guid Idannouncement { get; set; }
        public string Idprofile { get; set; } = null!;
        public string Title { get; set; } = null!;
        public string Description { get; set; } = null!;
        public string Location { get; set; } = null!;
        public string ExperienceLevel { get; set; } = null!;

        public virtual Profile IdprofileNavigation { get; set; } = null!;
        public virtual ICollection<Application> Applications { get; set; }
    }
}

JobsApp/Controllers/AnnouncementController.cs
using JobsApp.Data;
using JobsApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace JobsApp.Controllers
{
    public class AnnouncementController : Controller
    {
        private Repository.AnnouncementRepository _repository;

        public AnnouncementController(ApplicationDbContext dbContext)
        {
            _repository = new Repository.AnnouncementRepository(dbContext);
        }

        // GET: AnnouncementController
        public ActionResult Index()
        {
            var announcements = _repository.GetAllAnnouncements();
            return View("IndexAnnouncement", announcements);
        }

        [Authorize(Roles = "Company")]
        public ActionResult MyAnnouncements()
        {
            var announcements = _repository.GetAllAnnouncementsByProfile(User.Identity.Name);
            return View("MyAnnouncements", announcements);
        }

        // GET: AnnouncementController/Details/5
        public ActionResult Details(Guid id)
        {
            TempData["announcement"] = id;
            TempData["announcementApplications"] = id;
            var model = _repository.GetAnnouncementById(id);
            return View("AnnouncementDetails", model);
        }

        // GET: AnnouncementController/Create
        [Authorize(Roles = "Company")]
        public ActionResult Create()
        {
            var model = new AnnouncementModel();
            return View("CreateAnnouncement", model);
        }

        // POST: AnnouncementController/Create
        [Authorize(Roles = "Company")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                AnnouncementModel model = new AnnouncementModel();
                var task = TryUpdateModelAsync(model);
                task.Wait();
                _repository.InsertAnnouncement(model, User.Identity.Name);
                return View("CreateAnnouncement");
            }
            catch
            {
                return View("CreateAnnouncement");
            }
        }

        // GET: AnnouncementController/Edit/5
        [Authorize(Roles = "Company")]
        public ActionResult Edit(Guid id)
        {
            var model = _repository.GetAnnouncementById(id);
            return View("EditAnnouncement", model);
        }

        // POST: AnnouncementController/Edit/5
        [Authorize(Roles = "Company")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                var model = new AnnouncementModel();
                var task = TryUpdateModelAsync(model);
                task.Wait();
                _repository.UpdateAnnouncement(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index", id);
            }
        }

        // GET: AnnouncementController/Delete/5
        [Authorize(Roles = "Company")]
        public ActionResult Delete(Guid id)
        {
            var model = _repository.GetAnnouncementById(id);
            return View("DeleteAnnouncement", model);
        }

        // POST: AnnouncementController/Delete/5
        [Authorize(Roles = "Company")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                var model = _repository.GetAnnouncementById(id);
                _repository.DeleteAnnouncement(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("DeleteAnnouncement", id);
            }
        }
    }
}

JobsApp/Controllers/ApplicationController.cs
using JobsApp.Data;
using JobsApp.Models;
using JobsApp.Models.DBObjects;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace JobsApp.Controllers
{
    public class ApplicationController : Controller
    {
        private Repository.ApplicationRepository _repository;
        private Repository.AnnouncementRepository announcementRepository;

        public ApplicationController(ApplicationDbContext dbContext)
        {
            _repository = new Repository.ApplicationRepository(dbContext);
            announcementRepository = new Repository.AnnouncementRepository(dbContext);
        }

        // GET: ApplicationController
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Candidate")]
        public ActionResult MyApplications()
        {
            var myapplications = _repository.GetAllApplicationsByCandidateProfile(User.Identity.Name);
            return View("MyApplications", myapplications);
        }

        [Authorize(Roles = "Company")]
        public ActionResult ApplicationsToAnnouncement()
        {
            if (TempData["announcementApplications"] != null )
            {
                var announcementId = new Guid(TempData["announcementApplications"].ToString());
                var applicationsToAnnouncement = _repository.GetAllApplicationsByAnnouncement(announcementId);
                return View("ApplicationsToAnnouncement", applicationsToAnnouncement);
            }
            else
            {
                var myAnnouncements = announcementRepository.GetAllAnnouncementsByProfile(User.Identity.Name);
                return View("~/Views/Announcement/MyAnnouncements.cshtml", myAnnouncements);
            }    
        }

        // GET: ApplicationController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ApplicationController/Create
        [Authorize(Roles = "Candidate")]
        public ActionResult Create()
        {
            var model = new ApplicationModel();
            return View("CreateApplication", model);
        }

        // POST: ApplicationController/Create
        [Authorize(Roles = "Candidate")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                Models.ApplicationModel model = new Models.ApplicationModel();
                var announcement = new Guid(TempData["announcement"].ToString());
                var cv = new Guid(TempData["cv"].ToString());
                var task = TryUpdateModelAsync(model);
                task.Wait();
                _repository.InsertApplication(model, cv, announcement);
                return View("CreateApplication");
            }
            catch
            {
                return View("CreateApplication");
            }
        }

        // GET: ApplicationController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ApplicationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ApplicationController/Delete/5
        [Authorize(Roles = "Candidate")]
        public ActionResult Delete(Guid id)
        {
            var model = _repository.GetApplicationById(id);
            return View("Delete", model);
        }

        // POST: ApplicationController/Delete/5
        [Authorize(Roles = "Candidate")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                var model = _repository.GetApplicationById(id);
                _repository.DeleteApplication(model);
                return RedirectToAction("MyApplications");
            }
            catch
            {
                return View("Delete", id);
            }
        }
    }
}

JobsApp/Controllers/CvController.cs
using JobsApp.Data;
using JobsApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace JobsApp.Controllers
{
    public class CvController : Controller
    {
        private Repository.CVRepository _repository;

        public CvController(ApplicationDbContext dbContext)
        {
            _repository = new Repository.CVRepository(dbContext);
        }

        // GET: CvController
        public ActionResult Index()
        {
            var cvs = _repository.GetAllCVsByProfile(User.Identity.Name);
            return View("IndexCv", cvs);
        }

        public ActionResult ApplyList()
        {
            var cvs = _repository.GetAllCVsByProfile(User.Identity.Name);
            return View("ApplyList", cvs);
        }

        public ActionResult ApplyDetails(Guid id)
        {
            TempData["cv"] = id;
            var model = _repository.GetCVById(id);
            return View("ApplyDetails", model);
        }

        // GET: CvController/Details/5
        public ActionResult Details(Guid id)
        {
            var model = _repository.GetCVById(id);
            return View("CvDetails", model);
        }

        // GET: CvController/Create
        [Authorize(Roles = "Candidate")]
        public ActionResult Create()
        {
            var model = new CVModel();
            model.Mail = User.Identity.Name;
            return View("CreateCv", model);
        }


        // POST: CvController/Create
        [Authorize(Roles = "Candidate")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                Models.CVModel model = new Models.CVModel();

                var task = TryUpdateModelAsync(model);
                task.Wait();
                _repository.InsertCV(model, User.Identity.Name);
                return View("CreateCv");
            }
            catch
            {
                return View("CreateCv");
            }
        }

        // GET: CvController/Edit/5
        [Authorize(Roles = "Candidate")]
        public ActionResult Edit(Guid id)
        {
            var model = _repository.GetCVById(id);
            return View("EditCv", model);
        }

        // POST: CvController/Edit/5
        [Authorize(Roles = "Candidate")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                var model = new CVModel();
                var task = TryUpdateModelAsync(model);
                task.Wait();
                
                _repository.UpdateCV(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index", id);
            }
        }

        // GET: CvController/Delete/5
        [Authorize(Roles = "Candidate")]
        public ActionResult Delete(Guid id)
        {
            var model = _repository.GetCVById(id);
            return View("DeleteCv", model);
        }

        // POST: CvController/Delete/5
        [Authorize(Roles = "Candidate")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                var model = _repository.GetCVById(id);
                _repository.DeleteCV(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("DeleteCv", id);
            }
        }
    }
}

JobsApp/Controllers/ProfileController.cs
using JobsApp.Data;
using JobsApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace JobsApp.Controllers
{
    public class ProfileController : Controller
    {
        private Repository.ProfileRepository _repository;

        public ProfileController(ApplicationDbContext dbContext)
        {
            _repository = new Repository.ProfileRepository(dbContext);
        }

        [Authorize(Roles = "Candidate, Company, Admin")]
        // GET: ProfileController
        public ActionResult Index()
        {
            var profiles = _repository.GetAllProfiles();
            return View("IndexProfiles", profiles);
        }

        // GET: ProfileController/Details/5
        public ActionResult Details(string id)
        {
            var model = _repository.GetProfileById(id);
            return View("ProfileDetails", model);
        }
        
        [Authorize(Roles = "Candidate, Company, Admin")]
        // GET: ProfileController/Create
        public ActionResult Create()
        {
            var model = new ProfileModel();
            model.Idprofile = User.Identity.Name;
            return View("CreateProfile", model);
        }

        // POST: ProfileController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Candidate, Company, Admin")]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                Models.ProfileModel model = new Models.ProfileModel();

                var task = TryUpdateModelAsync(model);
                task.Wait();
                if (task.Result)
                {
                    _repository.InsertProfile(model);
                }

                return View("ProfileDetails", model);
            }
            catch
            {
                return View("CreateProfile");
            }
        }

        // GET: ProfileController/Edit/5
        public ActionResult Edit(string id)
        {
            var model = _repository.GetProfileById(id);
            return View("EditProfile", model);
        }

        // POST: ProfileController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, IFormCollection collection)
        {
            try
            {
                var model = new ProfileModel();

                var task = TryUpdateModelAsync(model);
                task.Wait();

                if (task.Result)
                {
                    _repository.UpdateProfile(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", id);
                }
            }
            catch
            {
                return RedirectToAction("Index", id);
            }
        }

        // GET: ProfileController/Delete/5
        public ActionResult Delete(string id)
        {
            var model = _repository.GetProfileById(id);
            return View("DeleteProfile", model);
        }

        // POST: ProfileController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id, IFormCollection collection)
        {
            try
            {
                var model = _repository.GetProfileById(id);
                _repository.DeleteProfile(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("DeleteProfile", id);
            }
        }
    }
}

JobsApp/Views/Announcement/AnnouncementDetails.cshtml
@model JobsApp.Models.AnnouncementModel

@{
    ViewData["Title"] = "AnnouncementDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Announcement Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExperienceLevel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExperienceLevel)
        </dd>
    </dl>
</div>
<div>
    @if (User.IsInRole("Candidate"))
    {
        <div>
            @Html.ActionLink("Apply", "ApplyList", "Cv", new {  id=Model.Idannouncement  })
        </div>
    }
    @if (User.Identity.Name == Model.Idprofile)
    {
        <div>
            @Html.ActionLink("Applications", "ApplicationsToAnnouncement", "Application", new {  id=Model.Idannouncement  })
        </div>   
    }
    @if (User.Identity.Name == Model.Idprofile)
    {
        <div>
            @Html.ActionLink("Edit", "Edit", new {  id = Model.Idannouncement  })
        </div>
    }
    <div>
        @Html.ActionLink("Company Details", "Details", "Profile", new {  id=Model.Idprofile  })
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

JobsApp/Views/Announcement/CreateAnnouncement.cshtml
@model JobsApp.Models.AnnouncementModel

@{
    ViewData["Title"] = "CreateAnnouncement";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create Announcement</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExperienceLevel" class="control-label"></label>
                <input asp-for="ExperienceLevel" class="form-control" />
                <span asp-validation-for="ExperienceLevel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JobsApp/Views/Announcement/DeleteAnnouncement.cshtml
@model JobsApp.Models.AnnouncementModel

@{
    ViewData["Title"] = "DeleteAnnouncement";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete Announcement</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExperienceLevel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExperienceLevel)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

JobsApp/Views/Announcement/EditAnnouncement.cshtml
@model JobsApp.Models.AnnouncementModel

@{
    ViewData["Title"] = "EditAnnouncement";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit Announcement</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExperienceLevel" class="control-label"></label>
                <input asp-for="ExperienceLevel" class="form-control" />
                <span asp-validation-for="ExperienceLevel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JobsApp/Views/Announcement/IndexAnnouncement.cshtml
@model IEnumerable<JobsApp.Models.AnnouncementModel>

@{
    ViewData["Title"] = "IndexAnnouncement";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Announcements</h1>

@if (User.IsInRole("Company"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExperienceLevel)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExperienceLevel)
            </td>
            <td>
                <div>
                    @Html.ActionLink("Details", "Details", new {  id=item.Idannouncement  })
                </div>
                @if (User.Identity.Name == item.Idprofile)
                {
                    <div>
                        @Html.ActionLink("Delete", "Delete", new {  id=item.Idannouncement  }) 
                    </div>
                    <div>
                        @Html.ActionLink("Edit", "Edit", new {  id=item.Idannouncement  })
                    </div>   
                }
            </td>
        </tr>
}
    </tbody>
</table>

JobsApp/Views/Announcement/MyAnnouncements.cshtml
@model IEnumerable<JobsApp.Models.AnnouncementModel>

@{
    ViewData["Title"] = "MyAnnouncements";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>My Announcements</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExperienceLevel)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExperienceLevel)
            </td>
            <td>
                <div>
                    @Html.ActionLink("Edit", "Edit", new {  id=item.Idannouncement  })
                </div>
                <div>
                    @Html.ActionLink("Details", "Details", new {  id=item.Idannouncement  })
                </div>
                <div>
                    @Html.ActionLink("Delete", "Delete", new {  id=item.Idannouncement  })
                </div>   
            </td>
        </tr>
}
    </tbody>
</table>